### ISSUE TITLE
Should boost force symbol visibility if built as a static lib?

### ISSUE THREAD

**Issue by epvbergen** [boostorg/throw_exception#9]
I'm consuming boost::asio as a static library in a project that is delivered as a shared library. To avoid conflicts in clients, I try to hide all symbols originating from my dependencies by linking with -Wl,--exclude-libs,ALL.

To my surprise, this does not work for boost::asio. A little research showed that at some point it was deemed a good idea to force default visibility on exception typeinfo and support classes for printing the exceptions from boost, see eg. https://svn.boost.org/trac10/ticket/4594 which proposed a #pragma visibility push default, only conditional on the compiler. So regardless of whether boost is built as a static or a dynamic library, the symbols get marked with default visibility on GCC.

And now I wonder if this is really the correct policy, or if boost (and any library) should rather refrain from explicitly setting visibility attributes when building a static library. Doesn't that make more sense?

Right now I have a nasty symbol leak that causes conflicts in my clients using a different version of asio. Updated: the problem has been reported before, along with a possible solution, see https://svn.boost.org/trac10/ticket/12722.

N.B.: moved here from https://github.com/boostorg/config/issues/243

**Comment by pdimov** [comment]
If exceptions are hidden, they can't be caught. Whether we're in a static library or not is not enough information; the static library may later be used as part of a shared library. (There are other problems with visibility too - the undefined behavior sanitizer can't validate virtual calls when the vtable/typeinfo are hidden, so all polymorphic classes used outside the library need to be visible too. Hidden visibility is quite tricky.)

**Comment by pdimov** [comment]
I assume that merging #10 has resolved this issue. The visibility of the exception classes is now controlled by BOOST_SYMBOL_VISIBLE, which is defined by Config.

**Comment by pdimov** [comment]
> Thanks, however please note the comment regarding placement at #10 (comment)#10, Replaced hardcoded symbol visibility for GCC with BOOST_SYMBOL_VISIBLE, as the patch would now break Windows DLL builds.

https://github.com/boostorg/throw_exception/commit/fe0f62bf1726cbc503ac664c24ac187bff789aae

**Comment by pdimov** [comment]
What I meant is that this is no longer an issue concerning `throw_exception`; it will be a decision controlled by Config, presumably through a user-defined macro that disables BOOST_SYMBOL_VISIBLE. This will then take effect throughout Boost.
